name: Docker Image CI

on: 
  push: 
    branches: [ "main" ]
  pull_request: 
    branches: [ "main" ]

jobs: 
  build-and-deploy:
    runs-on: ubuntu-latest

    steps: 
    - uses: actions/checkout@v4

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v2
      with:
        service_account_key: ${{ secrets.GCP_SERVICE_KEY }}
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        export_default_credentials: true

    - name: Build Docker image
      run: docker build . --file Dockerfile --tag gcr.io/${{ secrets.GCP_PROJECT_ID }}/imersao-devops-alura

    - name: Push Docker image to Google Container Registry
      run: |
        gcloud auth configure-docker
        docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/imersao-devops-alura

    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy imersao-devops-alura \
          --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/imersao-devops-alura \
          --region ${{ secrets.GCP_REGION }} \
          --platform managed \
          --allow-unauthenticated \
          --port 8000
