name: Docker Image CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          export_default_credentials: false

      - name: Write service account key to file
        shell: bash
        run: |
          echo "${{ secrets.GCP_SERVICE_KEY }}" > key.json

      - name: Activate service account
        run: |
          gcloud auth activate-service-account --key-file=key.json

      - name: Configure Docker authentication
        run: |
          gcloud auth configure-docker ${{ secrets.GCP_REGION }}-docker.pkg.dev --quiet

      - name: Build Docker image
        run: |
          docker build . --file Dockerfile --tag
